[package]
name = "crustc"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.95"
syn = { version = "2.0.101", features = ["full", "printing", "extra-traits"] }
annotate-snippets = "0.11.5"
libc = { path = "libs/libc" }

